### ISSUE TITLE
fromRight animation not applied on first display of lazy loaded scratchpad

### ISSUE THREAD

**Issue by dantefromhell** [hyprland-community/pyprland#18]
I configured a scratchpad for `pavucontrol` to be started lazily with `animation = fromRight`.

When I first open the scratchpad the animation comes from the left, re-opening the scratchpad after it's started applies the configured animation.
See video below, it helps to watch the video at 20% - 50% of the original speed.

Setting `lazy: false` applies the correct animation every time.

scratchpad config
```
"scratchpads": {                                                                                                  
  "volume": {                                                                                                     
    "command": "pavucontrol",                                                                                     
    "animation": "fromRight",                                                                                     
    "lazy": true,                                                                                                 
    "unfocus": "hide"                                                                                             
  }                                                                                                               
} 
```

https://github.com/hyprland-community/pyprland/assets/90508808/eb073615-7c89-4e89-8088-c2b212d83bf0

**Comment by fdev31** [comment]
This was decided a being technical limitation, `lazy` leads to a bogus first animation.
I have little interest in this feature (complexity added vs benefit) but maybe there is an easy implementation.

Did you try to play with the new "position" attribute and see if you could simulate the expected behavior ?

**Comment by fdev31** [comment]
This was decided a being technical limitation, `lazy` leads to a bogus first animation.
I have little interest in this feature (complexity added vs benefit) but maybe there is an easy implementation.

Did you try to play with the new "position" attribute and see if you could simulate the expected behavior ?

As far as I recall, it couldn't work due to animations. Creating the windows ahead of time allow to properly place them regardless of the animations duration, since the user have little chances to trigger the scratch right after it's created and before the animation ends this is not an issue.

PS: you'll see the same behavior when you close the app in the scratch and try to show it again, it's also considered a technical limitation. If you prove me wrong and there is a reasonably simple solution please re-open with your findings!
