### ISSUE TITLE
Feature request: Max scratchpad size / per monitor config

### ISSUE THREAD

**Issue by kuba-gaj** [hyprland-community/pyprland#30]
Hi, firstly let me thank you for this amazing project. Your scratchpad implementation is the best I found so far!

I would like you to consider adding an option for maximum width/height of the scratchpad window.
The problem I have is that I work with different screen ratios:
- 3:2 laptop (2256x1504)
- 16:9 monitors at work (mix of 1080p, 1440p and 4k)
- 32:9 monitor at home (5120x1440)

The main problem for me is the width at my ultrawide monitor at home. If i set up a scratchpad width for 80% it looks ok at my laptop and even at work, but it is way too wide on my 5120 ultrawide.

Ideally it would be great to be able to set maxWidth and maxHeight in pixels so it never gets bigger than these values on huge screens.

Another solution would  be a setting per monitor, but it would have to match per description as work and home are being connected to the same port on my laptop so it's not always same resolution.

On sway I just used absolute values in px for my scratchpad for something that works ok-ish on all monitors, so that would also help even though it's not ideal.

Thank you for your work!

**Comment by fdev31** [comment]
Hi and thank you !

I'll summarize:

- least preferred option: only add possibility to set the size in absolute pixels (instead of percentage)
- best option: on top of it, allow setting a `max_size`

Question: do you expect "hybrid" units to work, eg: `size="800px 30%"` (even though relative max sizes are making little sense, the format used & capabilities will probably be the same as for `size`)


PS: Just had a monitor change, so now I run into similar "problems" (didn't look optimal but didn't look too bad either)

**Comment by fdev31** [comment]
Just released 1.6.4, hope it does the job!

**Comment by kuba-gaj** [comment]
Amazing! Thank you for implementing it so quickly!
