### ISSUE TITLE
Scratchpad behaviour when switching workspaces

### ISSUE THREAD

**Issue by kuba-gaj** [hyprland-community/pyprland#32]
Hi, it's me again. 

I wonder you could consider improving the behaviour of scratchpad windows when switching workspaces as it is something I noticed recently.

1. Open scratchpad (e.g. term) window on current worskpace 1
2. Without closing it, switch to another workspace
3. Try to open the same scratchpad again

Current behaviour:
It switches you back to workspace 1 where the toggle hides the term

Expected behaviour
Have term from scratchpad open on the current workspace

What do you think?

**Comment by fdev31** [comment]
One fix I see would be to hide the scratchpad when we change the workspace (with a bit of logic to handle multiscreen scenarios).

Another option would be to check if the workspace we had the scratch displayed on is still displayed and then move the scratch instead of hiding it.

Those may require some additional calls to understand the state etc, I'm not sure the complexity is worth the feature... is the "main issue" that we switch workspaces to not see anything ? Then maybe the minimal fix could be to avoid this workspace change (so in this scenario, nothing would happen from the user perspective, if the action is repeated it will then work as expected).

I'll think about it, don't hesitate to tell me your opinion on the different options already mentioned.

**Comment by kuba-gaj** [comment]
So my workflow is that I use workspaces to group "projects", e.g.
- 1: work primary
- 2: work secondary
- 8: personal
- 9: learning

In scratchpads I keep apps that I want to have quick access to whichever workspace I'm on like:
- slack
- music streaming
- terminal

The problem is that for example I was doing work on `primary work` workspace, I opened a scratchpad there (let's say `slack`) and switched to the `secondary  work` workspace without closing slack or terminal. Now I realize I need to ask a colleague about something so I use my keybind to bring `slack` where I am, but what happens is that instead of slack window showing up it switches the workspace to the my main one and hides slack there.

The workspace switching is unexpected in this case, I don't want to need to remember what scratchpads are open where or developing a discipline of toggling them all of before I switch workspace. 

Ideally I would like for `pypr toggle` to:
- if scratchpad is opened on another workspace move it to current workspace as a scratchpad
- else toggle it on current workspace

If it's not possible the option of nothing happening (as I understand the would mean the scratchpad would hide on other workspace) and repeating the key bind would just open it in current workspace would be an improvment of the current behaviour.

**Comment by kuba-gaj** [comment]
Hiding scratchpad on workspace change would also improve it but I think it may be more complicated with multi screen setups, also could be jarring if I quickly switch between 2 workspaces and all scratchpads disappear from the first one, so I think it would be the least preferred option for me.

**Comment by fdev31** [comment]
Ok, I just made some relatively simple change which I find a good user experience.
It impacts the multi-screen scenarios, only the focused screen and workspace are considered.
Meaning if you move focus to another screen while having a scratchpad on one, then calling "toggle" will consider the scratchpad isn't visible in the proper workspace and will move the scratchpad instead of hidding it.
I believe this is a comparable or better UX. Do you have a chance to test the git version (or in the worst case, patch your local files temporarily) ?

**Comment by kuba-gaj** [comment]
Yes I'm happy to test it, but would need some instructions (I'm ok checking out the code but I'm not a python dev so may need some help with which command to run instead of pypr). Not sure I understood you correctly but in my opinion the scratchpad window should also be moved if it's on another workspace on the same monitor?

Thank you for your work and changes

**Comment by kuba-gaj** [comment]
I'm on arch so happy to test and even look into the code when I have a bit more time :)
Great, happy to test when there is a new release!

**Comment by kuba-gaj** [comment]
ok so I am testing using `pypr-git` package.

- Using the same monitor, opening scratchpad, switching to another workspace, and bringing the same scratchpad works as expected - there is no workspace switch and it appears (without animation like you mentioned above)
- There seem to be small regression - first time I open any scratchpad window the position is off
  - my `fromTop` scratchpad is shifted to the left
  - 'fromRight` is also shifted to the left
  - 'fromBottom` is shifted to the bottom
 - Toggling any of the scratchpad off and on fixes the position
 - on multimonitor setup it also works, this time with animation, but scratchpad windows are also shifted to wrong positon. Toggling them off and on on this monitor fixes it (but this happens every time I change workspace to different monitor

**Comment by fdev31** [comment]
Thank you for the report. I'll have a look in the next days most probably. The issue tot noticed happened not only with progressive apps isn't it ?

**Comment by fdev31** [comment]
FYI it was caused by some caching I added in the meantime, I reverted & published 1.6.5 including this improvement. In case you find any problem, the tracker is open ;)
Thank you, I experienced this bug from time to time but I really tend to always close the scratchpads or return to the same workspace to use it so I could never figure what was the scenario, so it really helped!

**Comment by kuba-gaj** [comment]
Thank you, when doing some more configuration today (not with scratchpads) I realized that having an option to `pin` the scratchpad would also help with this issue. Thank you for your work, it's a great plugin and much better than anything else I found!

**Comment by kuba-gaj** [comment]
Just tested and everything works great now, thank you very much!
